<a href="https://colab.research.google.com/github/yeison34k/diplomado_analisis_datos_machine_learning_python/blob/main/Notebook04_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="140px" src="https://upload.wikimedia.org/wikipedia/commons/archive/f/fb/20161010213812%21Escudo-UdeA.svg" align="left" hspace="10px" vspace="0px"></p>

# **Diplomado de Análisis de datos y Machine Learning en Python**


El presente diplomado hace parte del centro de Big Data de la facultad de ciencias exactas y naturales (FCEN) de la Universidad de Antioquia.

## **Sesión 7**

## **Contenido**

- <a href="#con"> Concatenación de arreglos</a><br> 
- <a href="#ind"> Indexación y segmentación</a><br>
- <a href="#enm"> Enmascaramiento
- <a href="#sof"> Indexación sofisticada</a><br></a><br>







# **Concatenación de arreglos**


La concatenación, o unión de dos arreglos en NumPy, se realiza principalmente a través de la función `concatenate`:

In [ ]:
import numpy as np

x = [1, 2, 3]
y = [4, 5, 6]

print(x + y)

[1, 2, 3, 4, 5, 6]


In [ ]:
xa = np.array(x)
ya = np.array(y)

print(np.concatenate((xa, ya)))

[1 2 3 4 5 6]


In [ ]:
print(np.concatenate((x, y)))

[1 2 3 4 5 6]


Podemos concatenar más de dos arreglos al tiempo:

In [ ]:
za = np.array([7, 8, 9])

print(np.concatenate((xa, ya, za)))

[1 2 3 4 5 6 7 8 9]


`concatenate` también se puede usar para arreglos bidimensionales. Recuerde que las filas corresponden al eje 1 (axis = 1) y las columnas al eje 0 (axis = 0)


<p><img alt="Colaboratory logo" height="300px" src="https://i.imgur.com/KYPgvhf.png" align="left" hspace="10px" vspace="0px"></p>

In [ ]:
a = np.arange(8,14).reshape(3,2)
print(a)

[[ 8  9]
 [10 11]
 [12 13]]


In [ ]:
np.concatenate([a,a], axis = 0)

array([[ 8,  9],
       [10, 11],
       [12, 13],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [ ]:
np.sum(a, axis=0)

array([30, 33])

Si queremos realizar la concatenación a lo largo del eje 1, debemos especificar el eje por medio de un argumento por palabra clave:

In [ ]:
np.concatenate([a,a], axis = 1)

array([[ 8,  9,  8,  9],
       [10, 11, 10, 11],
       [12, 13, 12, 13]])

La función `vstack()` es equivalente a la concatenación a lo largo del primer eje (axis=0). Al igual que `concatenate()`, recibe como argumento una secuencia de arreglos que, en este caso, deben tener la misma forma a lo largo de todos los ejes, excepto el primero. Los arreglos unidimensionales deben tener la misma longitud:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6],
              [7, 8, 9]])

print(f'a:\n {a}\nb:\n {b}')

a:
 [1 2 3]
b:
 [[4 5 6]
 [7 8 9]]


In [ ]:
print(a.shape, b.shape)

(3,) (2, 3)


In [ ]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Similarmente, la función `hstack()` realiza una concatenación a lo largo del segundo eje (axis=1), y los arreglos que toma como argumento deben coincidir en la forma a lo largo de este eje. Los arreglos unidimensionales pueden ser de cualquier longitud

In [ ]:
try:
  np.hstack((a,b))
except:
  print("No fue posible porque a y b no tienen la misma forma")

No fue posible porque a y b no tienen la misma forma


In [ ]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,11).reshape(2,2)

print(f'a:\n {a}\nb:\n {b}')

print(a.shape, b.shape)

np.hstack((a,b))

a:
 [[1 2 3]
 [4 5 6]]
b:
 [[ 7  8]
 [ 9 10]]
(2, 3) (2, 2)


array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

<p><a name="ind"></a></p>

# **Indexación y segmentación**

Los arreglos de NumPy tienen la misma semántica de indexación y segmentación que las listas de Python cuando se trata de acceder a elementos o subarreglos. 




In [ ]:
a = np.arange(8)

print(f"a\t: {a}")
print(f"a[2]\t: {a[0]}")
print(f"a[1:4]\t: {a[1 : 4]}")

a	: [0 1 2 3 4 5 6 7]
a[2]	: 0
a[1:4]	: [1 2 3]


Debido a que los arreglos de NumPy son n-dimensionales, podemos segmentar a lo largo de todos y cada uno de los ejes. Consideremos la siguiente lista de listas en Python

In [ ]:
l1 = [[1, 2], [3, 4]]
print(l1[0][1])

2


In [ ]:
L = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(L)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Por ejemplo, si queremos crear una lista de Python que contenga todas las filas y las primeras dos columnas de la lista L podríamos escribir

In [ ]:
[l[:2] for l in L]

[[1, 2], [4, 5], [7, 8]]

El número de ciclos `for` anidados que se necesita para segmentar listas de listas es igual al número de dimensiones menos uno (en este caso $2-1=1$). 

En NumPy, en lugar de indexar por un segmento, podemos indexar por una tupla de segmentos, cada uno de los cuales actúa en sus propias dimensiones. Definamos el arreglo `L` con NumPy y realicemos la segmentación anterior:


In [ ]:
L = np.arange(1,10).reshape(3,3)
print(L)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
L[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

Los ciclos `for` para la segmentación multidimensional son manejados implícitamente por NumPy. Esto hace que realizar segmentaciones complejas sea mucho más rápido que escribir los ciclos `for` explícitamente en Python. Veamos algunos ejemplos:

In [ ]:
a = np.arange(1,17).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#Seleccionar la primera fila
a[0]

array([1, 2, 3, 4])

In [ ]:
#Segmentar por la primera columna
a[:,0]

array([ 1,  5,  9, 13])

In [ ]:
#Segmentar por filas pares y columnas impares
a[::2,1::2]

array([[ 2,  4],
       [10, 12]])

In [ ]:
#Segmentar la matriz cuadrada interna
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
#Segmentar invirtiendo las 3 primeras filas, tomando las 3 ultimas columnas
a[2::-1,-3:]



array([[10, 11, 12],
       [ 6,  7,  8],
       [ 2,  3,  4]])

**Ejercicio 1**: Escriba un programa para crear un nuevo arreglo que sea el promedio de cada triplete consecutivo de elementos del siguiente arreglo

<p><img alt="Colaboratory logo" height="70px" src="https://i.imgur.com/XoHovZd.png" align="left" hspace="10px" vspace="0px"></p>

In [ ]:
a=np.array([1, 2, 3, 2, 4, 6, 1 ,2, 12, 0, -12, 6]).reshape(4,3)
print(a)
c = np.mean(a, axis=1)
print(c)

[[  1   2   3]
 [  2   4   6]
 [  1   2  12]
 [  0 -12   6]]
[ 2.  4.  5. -2.]


<p><a name="enm"></a></p>

## **Enmascaramiento**

El enmascaramiento aparece cuando deseamos extraer, modificar, o manipular valores en un arreglo de acuerdo con algún criterio.

Ya vimos cómo utilizar ufuncs para operaciones aritméticas básicas y otro tipo de operaciones más complejas. NumPy implementa también operadores de comparación como ufuncs:

In [ ]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x < 6

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

El resultado es un arreglo booleano. Dado un arreglo booleano, hay una serie de operaciones útiles que podemos implementar. 

Podemos utilizar la función `np.sum` junto con los operadores de comparación para realizar conteos dentro del arreglo:

In [ ]:
np.sum(x < 6)

5

Con `np.sum` podemos realizar este tipo de conteos a lo largo de las filas o columnas, utilizando el argumento por palabra clave `axis`:

In [ ]:
np.sum(x < 6 , axis = 0)

array([2, 2, 1])

In [ ]:
np.sum(x < 6 , axis = 1)

array([3, 2, 0])

Podemos también tener múltiples condiciones en un conteo, utilizando los operadores lógicos `&` (and) y `|` (or)

In [ ]:
print((x > 1) & (x < 5))
np.sum((x > 1) & (x < 5))

[[False  True  True]
 [ True False False]
 [False False False]]


3

In [ ]:
print((x > 6) | (x < 2))
np.sum((x > 6) | (x < 2))

[[ True False False]
 [False False False]
 [ True  True  True]]


4

Una herramienta muy poderosa es usar los arreglos booleanos como máscaras, para seleccionar subconjuntos particulares de los datos mismos. 

Volviendo a nuestra arreglo `x` anterior, supongamos que queremos un arreglo de todos los valores en `x` que sean menores que, digamos, 5. Para seleccionar estos valores del arreglo, simplemente podemos indexar con este arreglo booleano; esto se conoce como una operación de enmascaramiento:

In [ ]:
x[x < 6]

array([1, 2, 3, 4, 5])

Lo que se devuelve es un arreglo unidimensional con todos los valores que cumplen la condición; en otras palabras, todos los valores en las posiciones en las que el arreglo de máscara es `True`.

**Ejercicio 2:** Escriba una función que, dado un número entero `n`, muestre:

* Un arreglo con los primeros números pares hasta `n`.
* Un arreglo con los primeros números múltiplos de tres hasta `n`.

In [ ]:
def primeros_pares_mul3(n):
  
  a = np.arange(1, n+1)
  pares = a[ a % 2 == 0]
  mul3 = a[ a % 3 == 0]
  print(f"Los primeros pares son: {pares}")
  print(f"Los primeros multimplos de 3 son: {mul3}")

primeros_pares_mul3(12)

Los primeros pares son: [ 2  4  6  8 10 12]
Los primeros multimplos de 3 son: [ 3  6  9 12]


**Ejercicio 3:** Escribir un programa que lea `n` números enteros, calcule y muestre la suma de los pares y el producto de los impares.

In [ ]:
def suma_par_prod_impar(a):

  #a = np.array(l).astype("int")
  pares = a[ a % 2 == 0]
  impares = a[ a % 2 != 0]
  print(f"La suma de los pares es: {np.sum(pares)}")
  print(f"La multiplicación de impares es: {np.prod(impares)}")


lista = []
entrada = input("""Ingrese los números enteros separados por ",".\n""")
lista = entrada.split(',')
arr = np.array(lista).astype("int")
suma_par_prod_impar(arr)

Ingrese los números enteros separados por ",".
1,2,3,4
La suma de los pares es: 6
La multiplicación de impares es: 3


<p><a name="sof"></a></p>

# **Indexación sofisticada**

Anteriormente vimos cómo acceder y modificar porciones de arreglos usando índices simples (por ejemplo, `arr[0]`), segmentos (por ejemplo, `arr[: 5]`) y máscaras booleanas (por ejemplo, `arr[arr> 0]`). Veremos ahora otro estilo de indexación de arreglos, conocido como *indexación sofisticada*, la cual nos permite acceder y modificar muy rápidamente subconjuntos complicados de los valores de un arreglo.

La indexación sofisticada es conceptualmente simple: significa pasar una lista de índices en lugar de un entero, para acceder a múltiples elementos del arreglo a la vez. Veamos un ejemplo:

In [ ]:
a = np.arange(10, 20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
np.array([a[1], a[3], a[7]])

array([11, 13, 17])

In [ ]:
indices = [1, 3, 7]
print(a[indices])

[11 13 17]


Con el indexado sofisticado, la forma del resultado refleja la forma del arreglo de índices más que la forma del arreglo que se está indexando:

In [ ]:
a = np.arange(0,91,10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [ ]:
indi = np.array([[3, 7],
                 [4, 2]])

a[indi]

array([[30, 70],
       [40, 20]])

El indexado sofisticado funciona también en múltiples dimensiones. Veámoslo en el siguiente ejemplo:

In [ ]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Como en la indexación estándar, el primer índice hace referencia a las filas y el segundo a las columnas:

In [ ]:
fila  = [0, 1, 2]
colu = [2, 1, 3]

a[fila, colu]

array([ 2,  5, 11])

In [ ]:
np.array([a[0,2], a[1,1] ,a[2,3]])

array([ 2,  5, 11])

Los valores el en arreglo corresponden a `a[0,2]`, `a[1,1]` y `a[2,3]` respectivamente. 

In [ ]:
np.asarray?

In [ ]:
def sumaparesyProductoinpares(a):
  a=np.asarray(a).astype(int)
  print(a)
  pares = a[ a % 2 == 0]
  impares = a[ a % 2  != 0]
  print(f"La suma de los pares es: {np.sum(pares)}")
  print(f"La El producto de los impares es: {np.prod(impares)}")


l = [1,2,3,4,5]
sumaparesyProductoinpares(l)

[1 2 3 4 5]
La suma de los pares es: 6
La El producto de los impares es: 15
